/*
# Dedication Optimiser — Language Tutor

## Purpose
AI-powered language tutor: per-language assessment, generated curriculum
modules, tutor chat within modules, and adaptive follow-up module generation.

## New Tables

### language_assessments
One row per language per user. Created on first use of a language.
- id, user_id
- language (text, not null)
- level (text, check: beginner / some_knowledge / conversational)
- goal (text, what progress means for this language)
- style (text, check: vocabulary_heavy / grammar_first / conversation_first)
- ai_summary (text, AI-generated summary of the assessment)
- created_at

### language_modules
Curriculum modules generated by the AI based on assessment.
- id, user_id
- language (text, not null)
- module_number (integer, sequential per language per user)
- title (text)
- focus_area (text, check: vocabulary/grammar/listening/speaking/reading)
- content_json (jsonb, structured content for the module)
- completed (boolean, default false)
- created_at, completed_at

### language_tutor_messages
Chat messages within a module's tutor chat.
- id, user_id
- module_id (uuid, FK to language_modules)
- role (text, check: user/assistant)
- content (text)
- created_at

## Security
- RLS enabled on all tables, owner-scoped CRUD.
- module_id FK ensures tutor messages are scoped to user's own modules.
*/

-- Language assessments
CREATE TABLE IF NOT EXISTS language_assessments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  language text NOT NULL,
  level text NOT NULL,
  goal text NOT NULL,
  style text NOT NULL,
  ai_summary text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT language_assessments_level_check
    CHECK (level IN ('beginner','some_knowledge','conversational')),
  CONSTRAINT language_assessments_style_check
    CHECK (style IN ('vocabulary_heavy','grammar_first','conversation_first')),
  UNIQUE (user_id, language)
);

ALTER TABLE language_assessments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_language_assessments" ON language_assessments;
CREATE POLICY "select_own_language_assessments" ON language_assessments FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_language_assessments" ON language_assessments;
CREATE POLICY "insert_own_language_assessments" ON language_assessments FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_language_assessments" ON language_assessments;
CREATE POLICY "update_own_language_assessments" ON language_assessments FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_language_assessments" ON language_assessments;
CREATE POLICY "delete_own_language_assessments" ON language_assessments FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS language_assessments_user_idx
  ON language_assessments (user_id, language);

-- Language modules
CREATE TABLE IF NOT EXISTS language_modules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  language text NOT NULL,
  module_number integer NOT NULL,
  title text NOT NULL,
  focus_area text NOT NULL,
  content_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  completed boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  CONSTRAINT language_modules_focus_area_check
    CHECK (focus_area IN ('vocabulary','grammar','listening','speaking','reading'))
);

ALTER TABLE language_modules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_language_modules" ON language_modules;
CREATE POLICY "select_own_language_modules" ON language_modules FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_language_modules" ON language_modules;
CREATE POLICY "insert_own_language_modules" ON language_modules FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_language_modules" ON language_modules;
CREATE POLICY "update_own_language_modules" ON language_modules FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_language_modules" ON language_modules;
CREATE POLICY "delete_own_language_modules" ON language_modules FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS language_modules_user_lang_idx
  ON language_modules (user_id, language, module_number);

-- Language tutor messages
CREATE TABLE IF NOT EXISTS language_tutor_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  module_id uuid NOT NULL REFERENCES language_modules(id) ON DELETE CASCADE,
  role text NOT NULL,
  content text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT language_tutor_messages_role_check
    CHECK (role IN ('user','assistant'))
);

ALTER TABLE language_tutor_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_language_tutor_messages" ON language_tutor_messages;
CREATE POLICY "select_own_language_tutor_messages" ON language_tutor_messages FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_language_tutor_messages" ON language_tutor_messages;
CREATE POLICY "insert_own_language_tutor_messages" ON language_tutor_messages FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_language_tutor_messages" ON language_tutor_messages;
CREATE POLICY "update_own_language_tutor_messages" ON language_tutor_messages FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_language_tutor_messages" ON language_tutor_messages;
CREATE POLICY "delete_own_language_tutor_messages" ON language_tutor_messages FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS language_tutor_messages_module_idx
  ON language_tutor_messages (module_id, created_at);
