/*
# Dedication Optimiser — Gym Module (AI Trainer)

## Purpose
AI-powered gym trainer, mirroring the language module's pattern:
assessment -> AI-generated week plan -> session logging via the universal
timer -> a recovery check-in -> adaptive next week's plan. Also tracks PRs.

## New Tables

### gym_assessments
One row per user (re-taking the assessment overwrites it via upsert).
- id, user_id (unique)
- goal (text, check: strength/hypertrophy/general_fitness/endurance)
- experience_level (text, check: beginner/intermediate/advanced)
- days_per_week (integer)
- equipment (text, check: full_gym/home_dumbbells/bodyweight)
- injuries_notes (text, optional — injuries/limitations to work around)
- ai_summary (text, AI-generated summary of the assessment)
- created_at

### gym_plans
Weekly training plans generated by the AI based on the assessment
(and, from week 2 onward, the prior week's check-in + logged sessions + PRs).
- id, user_id
- week_number (integer, sequential per user)
- title (text)
- is_deload (boolean, default false — AI sets this when recovery signals call for it)
- content_json (jsonb — { intro, days: [{ day_label, focus, exercises: [{name,sets,reps,rest_sec,notes}] }], recovery_notes })
- completed (boolean, default false)
- created_at, completed_at

### gym_checkins
Recovery/deload check-in, submitted when a week is marked complete and used
to inform the next week's plan.
- id, user_id
- week_number (integer, which week this check-in follows)
- soreness (integer, 1-5)
- sleep_quality (integer, 1-5)
- motivation (integer, 1-5)
- pain_flag (boolean, default false — any pain, not just soreness)
- notes (text, optional)
- created_at

### gym_prs
Personal record log — free-form so any exercise/rep scheme can be logged.
- id, user_id
- exercise (text, e.g. "Back Squat")
- value (text, e.g. "100kg x 5" — kept as text for flexibility)
- achieved_at (date, default today)
- note (text, optional)
- created_at

## Security
- RLS enabled on all tables, owner-scoped CRUD.
*/

-- Gym assessments
CREATE TABLE IF NOT EXISTS gym_assessments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  goal text NOT NULL,
  experience_level text NOT NULL,
  days_per_week integer NOT NULL,
  equipment text NOT NULL,
  injuries_notes text,
  ai_summary text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT gym_assessments_goal_check
    CHECK (goal IN ('strength','hypertrophy','general_fitness','endurance')),
  CONSTRAINT gym_assessments_experience_check
    CHECK (experience_level IN ('beginner','intermediate','advanced')),
  CONSTRAINT gym_assessments_equipment_check
    CHECK (equipment IN ('full_gym','home_dumbbells','bodyweight')),
  CONSTRAINT gym_assessments_days_check
    CHECK (days_per_week BETWEEN 1 AND 7),
  UNIQUE (user_id)
);

ALTER TABLE gym_assessments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_gym_assessments" ON gym_assessments;
CREATE POLICY "select_own_gym_assessments" ON gym_assessments FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_gym_assessments" ON gym_assessments;
CREATE POLICY "insert_own_gym_assessments" ON gym_assessments FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_gym_assessments" ON gym_assessments;
CREATE POLICY "update_own_gym_assessments" ON gym_assessments FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_gym_assessments" ON gym_assessments;
CREATE POLICY "delete_own_gym_assessments" ON gym_assessments FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- Gym plans (weekly)
CREATE TABLE IF NOT EXISTS gym_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  week_number integer NOT NULL,
  title text NOT NULL,
  is_deload boolean NOT NULL DEFAULT false,
  content_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  completed boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

ALTER TABLE gym_plans ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_gym_plans" ON gym_plans;
CREATE POLICY "select_own_gym_plans" ON gym_plans FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_gym_plans" ON gym_plans;
CREATE POLICY "insert_own_gym_plans" ON gym_plans FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_gym_plans" ON gym_plans;
CREATE POLICY "update_own_gym_plans" ON gym_plans FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_gym_plans" ON gym_plans;
CREATE POLICY "delete_own_gym_plans" ON gym_plans FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS gym_plans_user_week_idx
  ON gym_plans (user_id, week_number);

-- Gym recovery/deload check-ins
CREATE TABLE IF NOT EXISTS gym_checkins (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  week_number integer NOT NULL,
  soreness integer NOT NULL,
  sleep_quality integer NOT NULL,
  motivation integer NOT NULL,
  pain_flag boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT gym_checkins_soreness_check CHECK (soreness BETWEEN 1 AND 5),
  CONSTRAINT gym_checkins_sleep_check CHECK (sleep_quality BETWEEN 1 AND 5),
  CONSTRAINT gym_checkins_motivation_check CHECK (motivation BETWEEN 1 AND 5)
);

ALTER TABLE gym_checkins ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_gym_checkins" ON gym_checkins;
CREATE POLICY "select_own_gym_checkins" ON gym_checkins FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_gym_checkins" ON gym_checkins;
CREATE POLICY "insert_own_gym_checkins" ON gym_checkins FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_gym_checkins" ON gym_checkins;
CREATE POLICY "update_own_gym_checkins" ON gym_checkins FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_gym_checkins" ON gym_checkins;
CREATE POLICY "delete_own_gym_checkins" ON gym_checkins FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS gym_checkins_user_week_idx
  ON gym_checkins (user_id, week_number DESC);

-- Gym personal records
CREATE TABLE IF NOT EXISTS gym_prs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  exercise text NOT NULL,
  value text NOT NULL,
  achieved_at date NOT NULL DEFAULT ((now() AT TIME ZONE 'UTC'::text))::date,
  note text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE gym_prs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_gym_prs" ON gym_prs;
CREATE POLICY "select_own_gym_prs" ON gym_prs FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_gym_prs" ON gym_prs;
CREATE POLICY "insert_own_gym_prs" ON gym_prs FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_gym_prs" ON gym_prs;
CREATE POLICY "update_own_gym_prs" ON gym_prs FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_gym_prs" ON gym_prs;
CREATE POLICY "delete_own_gym_prs" ON gym_prs FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS gym_prs_user_achieved_idx
  ON gym_prs (user_id, achieved_at DESC);
